// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1snaCBCTMza0cOM1BHXcos5WubpJdUU',
    appId: '1:675980340468:web:0e51763ce4e0c9ba3d02a1',
    messagingSenderId: '675980340468',
    projectId: 'nostracode-005',
    authDomain: 'nostracode-005.firebaseapp.com',
    storageBucket: 'nostracode-005.firebasestorage.app',
    measurementId: 'G-HPYL4VH55N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASJSuCAMjOb0DZwqvmAARKsjVLH447NF8',
    appId: '1:675980340468:ios:ed1f7cd5d4d8b8ec3d02a1',
    messagingSenderId: '675980340468',
    projectId: 'nostracode-005',
    storageBucket: 'nostracode-005.firebasestorage.app',
    iosClientId: '675980340468-1poeqbr7fg9vnu3n4dpgdu63kcinffao.apps.googleusercontent.com',
    iosBundleId: 'com.example.nc005',
  );
}
